# GUI
fps: {
  flake.modules.nixos.graphical = {
    # Configure keymap in X11;
    xserver.xkb = {
      layout = "us";
      variant = "";
    };
  };

  flake.modules.darwin.graphical = {pkgs, ...}: {
    environment.systemPackages = with pkgs; [
      raycast
    ];
  };

  # Hand rolled Hammerspoon module
  flake.modules.homeManager.mod-hammerspoon = {
    config,
    lib,
    pkgs,
    ...
  }: {
    options.programs.hammerspoon = {
      enable = lib.mkEnableOption "Hammerspoon";

      extraConfig = lib.mkOption {
        type = lib.types.lines;
        default = "";
        description = "Lua config snippets (concatenated from all modules)";
      };
    };

    config = lib.mkIf config.programs.hammerspoon.enable {
      home.file.".hammerspoon/init.lua".text = ''
        -- Hammerspoon configuration
        -- Generated by Home Manager
        -- Logs available in Hammerspoon Console (menu bar → Console)

        -- Auto-reload config when file changes
        hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", hs.reload):start()

        ${config.programs.hammerspoon.extraConfig}
      '';
    };
  };

  flake.modules.homeManager.graphical = {
    config,
    pkgs,
    lib,
    ...
  }:
    fps.jlib.mkHomeManager pkgs {
      generic = let
        # `clip` comes from the cli profile (always co-imported at host level).
        copy-last-cmd = pkgs.writeShellScriptBin "copy-last-cmd" ''
          cmd=$(${pkgs.nushell}/bin/nu -c 'history | last | get command')
          output=$(kitty @ get-text --extent last_non_empty_output)
          printf '$ %s\n%s' "$cmd" "$output" | clip
        '';
      in {
        home.packages = with pkgs; [
          copy-last-cmd
          neovide # Neovim GUI
          notify # Cross-platform notifications
          ffmpeg # Media processing toolkit
          usbutils # USB utilities
        ];

        programs.zathura.enable = true;
      };

      darwin = {
        imports = [
          fps.flake.modules.homeManager.mod-hammerspoon
        ];

        programs = {
          hammerspoon = {
            enable = true;
            extraConfig = builtins.readFile ./hammerspoon.lua;
          };

          # These are darwin specific because NixOS relies on the WM for splits.
          kitty = {
            settings = {
              macos_option_as_alt = true;
              macos_titlebar_color = "background";
              # macOS GUI apps don't inherit shell PATH, so tell kitty where to find nvim
              exe_search_path = "/etc/profiles/per-user/${config.home.username}/bin";
            };
            keybindings = {
              "cmd+p" = "previous_tab";
              "cmd+n" = "next_tab";
              "cmd+shift+p" = "move_tab_backward";
              "cmd+shift+n" = "move_tab_forward";
              "cmd+k" = "focus_visible_window";
              "cmd+shift+r" = "set_tab_title";
              "cmd+h" = "previous_window";
              "cmd+l" = "next_window";
              "cmd+enter" = "new_window_with_cwd";
            };
          };
          nushell.shellAliases.nv = "neovide --frame transparent --fork";
        };
      };
    };
}
