# Hammerspoon configuration module
# Allows multiple modules to contribute config snippets via extraConfig
{
  config,
  lib,
  pkgs,
  ...
}: {
  options.programs.hammerspoon = {
    enable = lib.mkEnableOption "Hammerspoon";

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Lua config snippets (concatenated from all modules)";
    };
  };

  config = lib.mkIf config.programs.hammerspoon.enable {
    home.file.".hammerspoon/init.lua".text = ''
      -- Hammerspoon configuration
      -- Generated by Home Manager
      -- Logs available in Hammerspoon Console (menu bar → Console)

      -- Auto-reload config when file changes
      hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", hs.reload):start()

      ${config.programs.hammerspoon.extraConfig}
    '';
  };
}
